CLASS zcl_local_event_matbomitmadd DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC FOR EVENTS OF zi_materialbomitemaddtp.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_LOCAL_EVENT_MATBOMITMADD IMPLEMENTATION.
ENDCLASS.
